title: "Zaida Martinez"
author: "Zaida Martinez"
description: "A personal website to share my interests and research"
baseurl: ""
url: "https://zaidaemtzmo.github.io"

# Theme (you can customize this)
theme: jekyll-theme-cayman

# Navigation Links
# nav_links:
#   Home: "/"
#   Research: "/research"
nav_links:
  Home: "{{ site.baseurl }}/"
  Research: "{{ site.baseurl }}/research"

sass:
  style: none

exclude:
  - _sass
  - assets/css/*.scss
