title: "Zaida Escila Martínez Moreno"
author: "Zaida Escila Martínez Moreno"
description: "A personal website to share my interests and research"
baseurl: ""
url: "https://zaidaemtzmo.github.io"

# Theme setup
theme: null
sass:
  style: none
exclude:
  - _sass
  - assets/css/*.scss

# Default language
lang: en

# Supported languages
languages:
  - en
  - es
  - fr

defaults:
  - scope:
      path: ""
    values:
      lang: "en"
  - scope:
      path: "_posts/en"
      type: "posts"
    values:
      permalink: "/en/all-posts/:year/:month/:day/:title.html"
  - scope:
      path: "_posts/es"
      type: "posts"
    values:
      permalink: "/es/all-posts/:year/:month/:day/:title.html"
  - scope:
      path: "_posts/fr"
      type: "posts"
    values:
      permalink: "/fr/all-posts/:year/:month/:day/:title.html"

# Navigation Links
nav_links:
  en:
    Home: "/en/"
    Research: "/en/research"
    AllPosts: "/en/all-posts"
  es:
    Home: "/es/"
    Research: "/es/research"
    AllPosts: "/es/all-posts"
  fr:
    Home: "/fr/"
    Research: "/fr/research"
    AllPosts: "/fr/all-posts"

# Month translations
months:
  en: [January, February, March, April, May, June, July, August, September, October, November, December]
  es: [Enero, Febrero, Marzo, Abril, Mayo, Junio, Julio, Agosto, Septiembre, Octubre, Noviembre, Diciembre]
  fr: [Janvier, Février, Mars, Avril, Mai, Juin, Juillet, Août, Septembre, Octobre, Novembre, Décembre]
